Repository ormcamp-fe-3rd/swim360, pull requests merged in 2024-12, with the labels that each got.

#1 [반재영,신명희] 모델 관계 설정
  back-end/models/index.js
Labels: enhancement

#3 [신명희] README.md 수정
  README.md
Labels: documentation

#4 [신명희] README.md a link 주소 지우기
  README.md
Labels: documentation, invalid

#10 [신명희] types 파일 생성
  frontend/src/types/cart.ts
  frontend/src/types/categories.ts
  frontend/src/types/discounts.ts
  frontend/src/types/orders.ts
  frontend/src/types/products.ts
  frontend/src/types/reviews.ts
  frontend/src/types/users.ts
Labels: enhancement

#11 [신명희] backend 모델 수정
  backend/models/Product.js
  backend/models/Review.js
  backend/models/User.js
Labels: invalid

#14 [신명희] ConfirmButton 구현, tailwind config 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/icon-reviews.png
  frontend/src/components/common/ConfirmButton.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/routes/pages/ProductList.tsx
  frontend/src/styles/output.css
  frontend/tailwind.config.js
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: bug, enhancement

#15 [신명희] breakpoint (tailwind.config)
  frontend/tailwind.config.js
Labels: enhancement, layout

#31 [김혜빈] 제품 상세페이지 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/common/btn-close.png
  frontend/public/images/common/btn-next.png
  frontend/public/images/common/btn-previous.png
  frontend/public/images/product/btn-input-image.png
  frontend/public/images/product/icon-add.png
  frontend/public/images/product/icon-delete.png
  frontend/public/images/product/icon-fabric-1.png
  frontend/public/images/product/icon-fabric-2.png
  frontend/public/images/product/icon-fabric-3.png
  frontend/public/images/product/icon-fabric-4.png
  frontend/public/images/product/icon-fabric-5.png
  frontend/public/images/product/icon-fabric-6.png
  frontend/public/images/product/icon-minus.png
  frontend/public/images/product/review-star-none.png
  frontend/public/images/product/review-star-selected.png
  frontend/src/components/common/Paginaion.tsx
  frontend/src/components/product/Component.tsx
  frontend/src/components/product/Details.tsx
  frontend/src/components/product/DetailsTab.tsx
  frontend/src/components/product/Photos.tsx
  frontend/src/components/product/QnasTab.tsx
  frontend/src/components/product/ReviewDetailModal.tsx
  frontend/src/components/product/ReviewWriteModal.tsx
  frontend/src/components/product/Reviews.tsx
  frontend/src/components/product/exchangeTab.tsx
  frontend/src/components/product/reviewsStar.tsx
  frontend/src/components/product/reviewsTab.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/carousel.tsx
  frontend/src/components/ui/pagination.tsx
  frontend/src/components/ui/textarea.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/Product.tsx
  frontend/src/styles/output.css
Labels: layout

#32 [김지균] 로그인페이지 UI 구현
  frontend/package-lock.json
  frontend/public/images/icon-reviews.png
  frontend/src/main.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/LoginPage.tsx
  frontend/src/styles/output.css
Labels: layout

#34 [김지균] 회원가입 페이지 UI 구현
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/JoinPage.tsx
Labels: layout

#35 [김지균]회원가입 약관 동의 페이지 UI 구현
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/AgreesPage.tsx
Labels: layout

#30 [신명희] 마이페이지 구현
  frontend/public/images/icon-reviews.png
  frontend/public/images/mypage/icon-mypage-user.png
  frontend/public/images/mypage/sample-1.png
  frontend/public/images/mypage/sample-2.png
  frontend/public/images/mypage/sample-3.png
  frontend/src/components/mypage/Component.tsx
  frontend/src/components/mypage/OrderStatusPreview.tsx
  frontend/src/components/mypage/RecentOrderPreview.tsx
  frontend/src/components/mypage/UserInfoPreview.tsx
  frontend/src/components/mypage/UserPointAndReviewPreview.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/MyPage.tsx
Labels: layout

#40 [ 김지균 ] 회원가입 완료 페이지 UI 구현
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/JoinCompletionPage.tsx
  frontend/src/routes/pages/LoginPage.tsx
Labels: 🎨 layout

#42 [ 김지균 ] 비밀번호 변경 완료 UI 구현
  frontend/src/components/common/PrimaryButton.tsx
  frontend/src/components/ui/tabs.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/ChangePwdCompletionPage.tsx
Labels: 🎨 layout

#45 [김지균] 주문/결제 완료 화면 UI 구현
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/PayMentCompletionPage.tsx
Labels: 🎨 layout

#41 [김혜빈] product 반응형 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/product/review-img-01.jpg
  frontend/public/images/product/swimsuit-back.jpg
  frontend/public/images/product/swimsuit-back2.jpg
  frontend/public/images/product/swimsuit-front.jpg
  frontend/public/images/product/swimsuit-front2.jpg
  frontend/public/images/product/swimsuit-side.jpg
  frontend/src/components/product/Details.tsx
  frontend/src/components/product/DetailsTab.tsx
  frontend/src/components/product/QnasTab.tsx
  frontend/src/components/product/ReviewDetailModal.tsx
  frontend/src/components/product/Reviews.tsx
  frontend/src/components/product/exchangeTab.tsx
  frontend/src/components/product/reviewsTab.tsx
  frontend/src/components/ui/accordion.tsx
  frontend/src/components/ui/carousel-origin.tsx
  frontend/src/routes/pages/Product.tsx
  frontend/tailwind.config.js
Labels: 🎨 layout, 👀 team review

#44 [신명희] 상품 목록 페이지 레이아웃, 상품 목록 아이템, 공통 버튼(Primary Button) 수정
  frontend/public/images/productlist/sample-2.png
  frontend/src/components/home/Footer.tsx
  frontend/src/components/product-list/ProductItem.tsx
  frontend/src/components/product-list/ProductItemList.tsx
  frontend/src/components/product-list/Sidebar.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/ProductListPage.tsx
  frontend/src/styles/output.css
  frontend/src/types/products.ts
Labels: 🔋 enhancement, 🎨 layout, 👀 team review

#43 [신명희] 마이페이지 레이아웃
  backend/.env
  frontend/src/components/mypage/OrderStatusPreview.tsx
  frontend/src/components/mypage/RecentOrderPreview.tsx
  frontend/src/components/mypage/UserInfoPreview.tsx
  frontend/src/components/mypage/UserPointAndReviewPreview.tsx
  frontend/src/routes/pages/MyPage.tsx
Labels: 🎨 layout, 👀 team review

#36 [반재영] 메인 카테고리/반응형 수정, 개인정보수정/포인트페이지 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/home/button-left-white.png
  frontend/public/images/home/icon-fins.png
  frontend/public/images/home/icon-full-body.png
  frontend/public/images/home/icon-mid-length.png
  frontend/public/images/home/icon-one-piece.png
  frontend/public/images/home/icon-square-cut.png
  frontend/src/components/common/PrimaryButton.tsx
  frontend/src/components/home/BestPick.tsx
  frontend/src/components/home/CarouselBanner.tsx
  frontend/src/components/home/CarouselBestpick.tsx
  frontend/src/components/home/CategoryBox.tsx
  frontend/src/components/home/CategoryHoberBox.tsx
  frontend/src/components/home/CategoryHoberList.tsx
  frontend/src/components/home/CategoryList.tsx
  frontend/src/components/home/CategoryUnderline.tsx
  frontend/src/components/mypage/PointAndReviewList.tsx
  frontend/src/components/mypage/PointAndReviewTab.tsx
  frontend/src/components/mypage/UserInfoEdit.tsx
  frontend/src/components/mypage/UserInfoEditForm.tsx
  frontend/src/components/mypage/UserInfoEditVerification.tsx
  frontend/src/components/product-list/ProductItem.tsx
  frontend/src/components/product/ReviewDetailModal.tsx
  frontend/src/components/product/ReviewWriteModal.tsx
  frontend/src/components/product/reviewsTab.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/carousel.tsx
  frontend/src/components/ui/form.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/components/ui/pagination.tsx
  frontend/src/components/ui/table.tsx
  frontend/src/main.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/MyPageEdit.tsx
Labels: 🎨 layout, 👀 team review

#38 [김지균] 결제/주문 페이지 UI 구현
  frontend/src/components/ui/breadcrumb.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/PayMentOrderPage.tsx
Labels: 🎨 layout, 👀 team review

#46 [김혜빈] product 반응형 보완
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/product/Details.tsx
  frontend/src/components/product/DetailsTab.tsx
  frontend/src/components/product/Photos.tsx
  frontend/src/components/product/QnasTab.tsx
  frontend/src/components/product/Reviews.tsx
  frontend/src/components/product/exchangeTab.tsx
  frontend/src/components/product/reviewsTab.tsx
  frontend/src/components/ui/accordion.tsx
  frontend/src/components/ui/tabs.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/Product.tsx
Labels: 🎨 layout, 👀 team review

#47 [반재영] 메인 페이지 반응형 적용
  frontend/src/components/common/Footer.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/components/home/BestPick.tsx
  frontend/src/components/home/CarouselBestpick.tsx
  frontend/src/main.tsx
  frontend/src/routes/index.tsx
Labels: 🎨 layout, 👀 team review

#48 [반재영] 포인트, 리뷰페이지 UI 구현
  frontend/package-lock.json
  frontend/src/components/mypage/PointAndReview.tsx
  frontend/src/components/mypage/PointAndReviewList.tsx
  frontend/src/components/mypage/PointAndReviewTab.tsx
  frontend/src/components/mypage/PointList.tsx
  frontend/src/components/mypage/ReviewList.tsx
  frontend/src/components/mypage/UserEdit.tsx
  frontend/src/components/mypage/UserEditVeri.tsx
  frontend/src/components/mypage/UserInfoEdit.tsx
  frontend/src/components/mypage/UserInfoEditVerification.tsx
  frontend/src/components/mypage/UserPointAndReviewPreview.tsx
  frontend/src/components/ui/table.tsx
  frontend/src/components/ui/tabs.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/MyPageEdit.tsx
  frontend/src/routes/pages/MyPagePointAndReviewPage.tsx
  frontend/src/routes/pages/UserEditPage.tsx
  frontend/src/routes/pages/UserPage.tsx
Labels: 🎨 layout, 👀 team review, ⚡️ mentor review

#49 [신명희] 라우터 수정
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/routes/index.tsx
Labels: 🔋 enhancement, 🔨 invalid, 🌈 feature

#53 [반재영, 신명희] 마이페이지 관련 수정
  frontend/src/components/mypage/OrderStatusPreview.tsx
  frontend/src/components/mypage/PointAndReview.tsx
  frontend/src/components/mypage/RecentOrderPreview.tsx
  frontend/src/components/mypage/UserEditVeri.tsx
  frontend/src/components/mypage/UserInfoEditForm.tsx
  frontend/src/components/mypage/UserInfoPreview.tsx
  frontend/src/components/mypage/UserPointAndReviewPreview.tsx
  frontend/src/main.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/MyPageAuthPwPage.tsx
  frontend/src/routes/pages/MyPageEditPage.tsx
  frontend/src/routes/pages/PointAndReviewPage.tsx
  frontend/src/routes/pages/UserPage.tsx
Labels: ⚠️ bug, 🎨 layout

#56 [반재영] 카테고리 링크 연결, 햄버거메뉴 수정, 헤더 반응형 수정
  frontend/src/components/common/Header.tsx
  frontend/src/components/home/CategoryBox.tsx
  frontend/src/components/home/CategoryHoberBox.tsx
  frontend/src/components/home/CategoryHoberList.tsx
  frontend/src/components/home/CategoryList.tsx
  frontend/src/components/home/CategoryUnderline.tsx
  frontend/src/components/home/HamburgerMenu.tsx
  frontend/src/components/home/HamburgerMenuList.tsx
  frontend/src/components/home/MainLogo.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/ErrorPage.tsx
Labels: 🔨 invalid, 🎨 layout, 👀 team review

#55 [김지균] 반응형 , 주문/결제 페이지 컴포넌트화
  frontend/package-lock.json
  frontend/src/components/logIn/Component.tsx
  frontend/src/components/login/FindIdPwdTab.tsx
  frontend/src/components/paymentorder/MeansPayment.tsx
  frontend/src/components/paymentorder/OrderProductList.tsx
  frontend/src/components/paymentorder/PossessionPoint.tsx
  frontend/src/components/paymentorder/ShippingInformation.tsx
  frontend/src/components/paymentorder/TotalPrice.tsx
  frontend/src/components/ui/accordion.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/ChangePwdCompletionPage.tsx
  frontend/src/routes/pages/JoinCompletionPage.tsx
  frontend/src/routes/pages/JoinPage.tsx
  frontend/src/routes/pages/LoginPage.tsx
  frontend/src/routes/pages/PayMentCompletionPage.tsx
  frontend/src/routes/pages/PayMentOrderPage.tsx
  frontend/tailwind.config.js
  package-lock.json
Labels: 🎨 layout, 👀 team review, ⚡️ mentor review

#54 [신명희] 상품목록 왼쪽으로 쏠리는 디자인 수정 및 스크롤 초기화 추가
  frontend/src/App.tsx
  frontend/src/components/common/ScrollToTop.tsx
  frontend/src/routes/pages/ProductListPage.tsx
Labels: 🔨 invalid

#58 [신명희] routes/index.ts 수정
  frontend/src/routes/index.tsx
Labels: ⚠️ bug

#61 [신명희] README 추가
  README.md
Labels: 📄 documentation

#63 [반재영] 헤더 링크 오류 해결
  frontend/src/components/home/MainIconButton.tsx
  frontend/src/routes/index.tsx
Labels: 🔨 invalid

#71 [반재영] 카트 주문목록 padding 중복 삭제
  frontend/src/components/cart/CartProduct.tsx
Labels: 🎨 layout

#69 [반재영] 마이페이지 피드백 반영
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/mypage/PointAndReview.tsx
  frontend/src/components/mypage/PointList.tsx
  frontend/src/components/mypage/Points.tsx
  frontend/src/components/mypage/ReviewList.tsx
  frontend/src/components/mypage/Reviews.tsx
  frontend/src/components/mypage/UserEdit.tsx
  frontend/src/components/mypage/UserInfoEditForm.tsx
  frontend/src/components/mypage/UserVerification.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/MyPageAuthPwPage.tsx
  frontend/src/routes/pages/MyPageEditPage.tsx
  frontend/src/routes/pages/PointAndReviewPage.tsx
  frontend/src/routes/pages/UserVerificationPage.tsx
Labels: 🔋 enhancement

#67 [신명희] 마이페이지 피드백 반영
  frontend/src/components/mypage/OrderStatusPreview.tsx
  frontend/src/components/mypage/PointAndReviewItem.tsx
  frontend/src/components/mypage/PointAndReviewPreview.tsx
  frontend/src/components/mypage/RecentOrderPreview.tsx
  frontend/src/components/mypage/RecentOrders.tsx
  frontend/src/components/mypage/UserInfoPreview.tsx
  frontend/src/components/mypage/UserPointAndReviewPreview.tsx
  frontend/src/mocks/mypage.json
  frontend/src/routes/pages/MyPage.tsx
  frontend/src/types/orders.ts
Labels: 🔋 enhancement

#68 [신명희] 리뷰 받은 내용 상품 목록 페이지에도 적용
  frontend/src/components/product-list/ProductItem.tsx
  frontend/src/components/product-list/ProductItemList.tsx
  frontend/src/components/product-list/Sidebar.tsx
  frontend/src/components/product-list/SortSelect.tsx
  frontend/src/mocks/categories.json
  frontend/src/mocks/products.json
  frontend/src/routes/pages/ProductListPage.tsx
  frontend/src/types/products.ts
Labels: 🔋 enhancement

#73 [신명희] 장바구니 기능 추가
  frontend/src/App.tsx
  frontend/src/components/home/MainIconButton.tsx
  frontend/src/components/product/Details.tsx
  frontend/src/contexts/CartContext.tsx
  frontend/src/contexts/index.ts
  frontend/src/hooks/useCart.ts
Labels: 🌈 feature

#74 [신명희] 상품 목록의 Link 삭제
  frontend/src/components/product-list/ProductItem.tsx
  frontend/src/components/product-list/ProductItemList.tsx
Labels: ⚠️ bug

#75 [김혜빈] 탭 컨포먼트 생성, 피드백 반영 중간저장
  frontend/src/components/product/Details.tsx
  frontend/src/components/product/DetailsTab.tsx
  frontend/src/components/product/QnasTab.tsx
  frontend/src/components/product/ReviewDetailModal.tsx
  frontend/src/components/product/ReviewStar.tsx
  frontend/src/components/product/ReviewWriteModal.tsx
  frontend/src/components/product/Reviews.tsx
  frontend/src/components/product/Tap.tsx
  frontend/src/components/product/exchangeTab.tsx
  frontend/src/components/product/reviewsTab.tsx
  frontend/src/routes/pages/ProductDetailPage.tsx
Labels: 🔋 enhancement

#77 [전체] 백엔드 모델 필드 및 관계 수정
  backend/models/Discount.js
  backend/models/Order.js
  backend/models/OrderItem.js
  backend/models/Product.js
  backend/models/Review.js
  backend/models/User.js
  backend/models/index.js
Labels: 🌈 feature

#78 [신명희] axios cors 에러
  backend/app.js
  frontend/src/components/common/Header.tsx
  frontend/src/services/category.ts
  frontend/src/services/index.ts
Labels: ⚠️ bug

#82 [김혜빈] 상세페이지 피드백 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/product/Photos.tsx
  frontend/src/components/product/QnasTab.tsx
  frontend/src/components/product/Review.tsx
  frontend/src/components/product/ReviewDetailModal.tsx
  frontend/src/components/product/ReviewStar.tsx
  frontend/src/components/product/ReviewWriteModal.tsx
  frontend/src/components/product/Tap.tsx
  frontend/src/components/product/exchangeTab.tsx
  frontend/src/components/product/reviewsTab.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/mocks/reviews.json
  frontend/src/types/products.ts
  frontend/src/types/reviews.ts
Labels: 🔋 enhancement

#79 [신명희] 백엔드 Cart, Category 수정, Discount 테이블 생성 순서 변경
  backend/models/Cart.js
  backend/models/Category.js
  backend/models/index.js
  backend/package.json
Labels: 🔨 invalid

#80 [신명희] 장바구니 담기 클릭 기능 구현
  backend/routes/carts.js
  frontend/src/components/product/Details.tsx
  frontend/src/hooks/useCart.ts
  frontend/src/services/cart.ts
  frontend/src/types/cart.ts
Labels: 🌈 feature

#85 [반재영] IsLoginContext 추가, 회원별 리뷰내역 불러오기, 로그아웃
  backend/models/index.js
  backend/routes/products.js
  backend/routes/reviews.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/common/icon-logout.png
  frontend/src/App.tsx
  frontend/src/components/home/MainIconButton.tsx
  frontend/src/components/mypage/LogoutButton.tsx
  frontend/src/components/mypage/PointAndReview.tsx
  frontend/src/components/mypage/PointAndReviewPreview.tsx
  frontend/src/components/mypage/ReviewList.tsx
  frontend/src/components/mypage/Reviews.tsx
  frontend/src/components/ui/tooltip.tsx
  frontend/src/contexts/IsLoginContext.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/LoginPage.tsx
  frontend/src/routes/pages/MyPage.tsx
  frontend/src/services/user.ts
  frontend/src/types/reviews.ts
  frontend/src/types/users.ts
Labels: 🌈 feature, 👀 team review

#83 [신명희] 장바구니 기능 구현
  backend/routes/carts.js
  frontend/src/components/home/MainIconButton.tsx
  frontend/src/hooks/useCart.ts
  frontend/src/services/cart.ts
Labels: 🔋 enhancement, 🌈 feature, 👀 team review

#87 [신명희] 헤더의 카테고리와 연동하여 상품 목록 불러오는 기능 구현
  backend/models/Category.js
  backend/routes/categories.js
  backend/routes/products.js
  frontend/src/App.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/components/home/CategoryBox.tsx
  frontend/src/components/home/CategoryHoberBox.tsx
  frontend/src/components/home/HamburgerMenu.tsx
  frontend/src/components/product-list/ProductItem.tsx
  frontend/src/components/product-list/ProductItemList.tsx
  frontend/src/components/product-list/Sidebar.tsx
  frontend/src/components/product-list/SortSelect.tsx
  frontend/src/contexts/CategoryContext.tsx
  frontend/src/hooks/useCategory.ts
  frontend/src/hooks/useExample.ts
  frontend/src/hooks/useProducts.ts
  frontend/src/hooks/useToggle.ts
  frontend/src/routes/pages/ProductListPage.tsx
  frontend/src/services/category.ts
  frontend/src/services/product.ts
  frontend/src/types/categories.ts
  frontend/src/types/products.ts
Labels: 🌈 feature, ⚡️ mentor review

#90 [김혜빈] 상세페이지 db연결
  backend/routes/products.js
  backend/routes/reviews.js
  frontend/src/components/product/Details.tsx
  frontend/src/components/product/SelectedItem.tsx
  frontend/src/components/product/SizeBtn.tsx
  frontend/src/components/product/reviewsTab.tsx
  frontend/src/hooks/useProduct.ts
  frontend/src/hooks/useReview.ts
  frontend/src/services/product.ts
  frontend/src/types/products.ts
Labels: 🌈 feature, ⚡️ mentor review

#89 [반재영] 회원 리뷰내역, 주문내역 연동
  backend/models/Order.js
  backend/routes/index.js
  backend/routes/orderItems.js
  backend/routes/orders.js
  backend/routes/users.js
  frontend/src/App.tsx
  frontend/src/components/home/MainIconButton.tsx
  frontend/src/components/mypage/OrderStatusPreview.tsx
  frontend/src/components/mypage/PointAndReview.tsx
  frontend/src/components/mypage/PointAndReviewPreview.tsx
  frontend/src/components/mypage/RecentOrderItems.tsx
  frontend/src/components/mypage/RecentOrderPreview.tsx
  frontend/src/components/mypage/RecentOrders.tsx
  frontend/src/components/mypage/UserInfoPreview.tsx
  frontend/src/components/mypage/UserVerification.tsx
  frontend/src/contexts/UserContext.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/LoginPage.tsx
  frontend/src/routes/pages/MyPage.tsx
  frontend/src/services/orderItem.ts
  frontend/src/services/product.ts
  frontend/src/services/user.ts
  frontend/src/types/orders.ts
Labels: 🌈 feature, ⚡️ mentor review

#86 [김지균] 버튼 클릭시 페이지 이동, 전체 동의 체크 기능
  frontend/package-lock.json
  frontend/src/components/common/PrimaryButton.tsx
  frontend/src/components/join/Agrees.tsx
  frontend/src/components/login/FindIdPwdTab.tsx
  frontend/src/components/paymentorder/PriceRow.tsx
  frontend/src/components/ui/tabs.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/FindIdPwdPage.tsx
  frontend/src/routes/pages/JoinPage.tsx
  frontend/src/routes/pages/LoginPage.tsx
  frontend/src/routes/pages/MyPage.tsx
Labels: 🌈 feature

#88 [김지균] 상세페이지에서 상품 정보 주문/결제페이지로 가져오기
  frontend/src/components/paymentorder/OrderProductList.tsx
  frontend/src/components/paymentorder/PriceRow.tsx
  frontend/src/components/product/Details.tsx
  frontend/src/routes/pages/PayMentOrderPage.tsx
Labels: 🌈 feature, ⚡️ mentor review

#91 [전체] 타입 수정 및 에러 고침
  backend/models/Product.js
  backend/models/User.js
  backend/routes/orderItems.js
  backend/routes/products.js
  backend/routes/reviews.js
  frontend/src/components/mypage/RecentOrderItems.tsx
  frontend/src/components/product/Details.tsx
  frontend/src/hooks/useCart.ts
  frontend/src/hooks/useProduct.ts
  frontend/src/hooks/useProducts.ts
  frontend/src/routes/pages/ProductDetailPage.tsx
  frontend/src/routes/pages/ProductListPage.tsx
  frontend/src/services/product.ts
  frontend/src/types/products.ts
Labels: ⚠️ bug, 🔨 invalid, 🌈 feature

#92 [반재영] seedData 추가
  backend/app.js
  backend/models/index.js
  backend/seedData.js
Labels: 🌈 feature, 👀 team review

#94 [신명희] 헤더 및 상품 목록 페이지 코드 리뷰 반영
  backend/routes/categories.js
  backend/routes/products.js
  frontend/src/components/common/Header.tsx
  frontend/src/components/home/CategoryBox.tsx
  frontend/src/components/home/CategoryHoberList.tsx
  frontend/src/components/home/CategoryHoverBox.tsx
  frontend/src/components/home/CategoryList.tsx
  frontend/src/components/home/CategoryUnderline.tsx
  frontend/src/components/home/HamburgerMenu.tsx
  frontend/src/components/product-list/Sidebar.tsx
  frontend/src/components/product/Details.tsx
  frontend/src/contexts/CategoryContext.tsx
  frontend/src/hooks/useCategory.ts
  frontend/src/hooks/useProductList.ts
  frontend/src/hooks/useProducts.ts
  frontend/src/hooks/useToggle.ts
  frontend/src/routes/pages/ProductListPage.tsx
  frontend/src/services/product.ts
  frontend/src/types/products.ts
Labels: 🔋 enhancement

#97 [김지균] 상세페이지에서 주문내역 불러오기
  backend/models/OrderItem.js
  frontend/package-lock.json
  frontend/src/components/common/PrimaryButton.tsx
  frontend/src/components/paymentorder/OrderProductList.tsx
  frontend/src/components/paymentorder/PossessionPoint.tsx
  frontend/src/components/paymentorder/ShippingInformation.tsx
  frontend/src/components/paymentorder/TotalPrice.tsx
  frontend/src/components/product/Details.tsx
  frontend/src/routes/pages/PayMentOrderPage.tsx
  frontend/src/types/orders.ts
Labels: 🌈 feature

#96 [김혜빈] 리뷰 api 연동
  backend/routes/products.js
  backend/routes/reviews.js
  frontend/src/components/product/Details.tsx
  frontend/src/components/product/Review.tsx
  frontend/src/components/product/SelectedItem.tsx
  frontend/src/components/product/reviewsTab.tsx
  frontend/src/hooks/useProduct.ts
  frontend/src/hooks/useReview.ts
  frontend/src/routes/pages/ProductDetailPage.tsx
  frontend/src/services/product.ts
  frontend/src/types/products.ts
  frontend/src/types/reviews.ts
Labels: 🌈 feature

#102 [반재영] 메인 베스트상품 db 연동, 상품페이지 Link 연결, 상품 seedData 추가
  backend/app.js
  backend/public/images/product1-01.jpg
  backend/public/images/product1-02.jpg
  backend/public/images/product2-01.jpg
  backend/public/images/product2-02.jpg
  backend/public/images/product3-01.jpg
  backend/public/images/product3-02.jpg
  backend/public/images/product4-01.jpg
  backend/public/images/product4-02.jpg
  backend/public/images/product5-01.jpg
  backend/public/images/product5-02.jpg
  backend/public/images/product6-01.jpg
  backend/public/images/product6-02.jpg
  backend/public/images/product7-01.jpg
  backend/public/images/product7-02.jpg
  backend/routes/products.js
  backend/seedData.js
  frontend/src/components/home/BestPick.tsx
  frontend/src/components/home/CarouselBestpick.tsx
  frontend/src/components/product-list/ProductItem.tsx
  frontend/src/services/product.ts
  frontend/src/types/products.ts
Labels: 🌈 feature, 👀 team review

#98 [반재영] 2주차 멘토리뷰 반영
  backend/models/OrderItem.js
  backend/routes/orderItems.js
  backend/routes/orders.js
  backend/routes/reviews.js
  backend/routes/users.js
  frontend/src/App.tsx
  frontend/src/components/home/MainIconButton.tsx
  frontend/src/components/mypage/LogoutButton.tsx
  frontend/src/components/mypage/PointAndReview.tsx
  frontend/src/components/mypage/RecentOrderItems.tsx
  frontend/src/components/mypage/RecentOrders.tsx
  frontend/src/components/mypage/ReviewTable.tsx
  frontend/src/components/mypage/ReviewTableBody.tsx
  frontend/src/components/mypage/UserDetailPreview.tsx
  frontend/src/components/mypage/UserInfoPreview.tsx
  frontend/src/contexts/UserContext.tsx
  frontend/src/contexts/UserIdContext.tsx
  frontend/src/hooks/useUserId.ts
  frontend/src/routes/pages/LoginPage.tsx
  frontend/src/routes/pages/MyPage.tsx
  frontend/src/services/order.ts
  frontend/src/services/orderItem.ts
  frontend/src/services/user.ts
  frontend/src/types/orders.ts
  frontend/src/types/users.ts
  frontend/src/utils/formatPrice.ts
  frontend/src/utils/getLocalDate.ts
Labels: 🔋 enhancement, 🔨 invalid, 🌈 feature

#100 [신명희] 상품 목록 불러오기 실패 시 에러 처리
  frontend/src/components/common/Loader.tsx
  frontend/src/components/home/CategoryBox.tsx
  frontend/src/components/home/HamburgerMenu.tsx
  frontend/src/hooks/useCategory.ts
  frontend/src/hooks/useProductList.ts
  frontend/src/routes/pages/ProductListPage.tsx
  frontend/src/services/product.ts
Labels: ⚠️ bug, 🔋 enhancement, 🌈 feature

#101 [신명희] 장바구니 불러오기 실패 시 에러 처리 및 장바구니 업데이트 시점 수정
  frontend/src/components/cart/CartProductList.tsx
  frontend/src/components/home/MainIconButton.tsx
  frontend/src/hooks/useCart.ts
Labels: ⚠️ bug, 🔋 enhancement, 🌈 feature

#103 [신명희] Bestpick 및 ProductItem 타입 ProductItem으로 변경
  frontend/src/components/home/BestPick.tsx
  frontend/src/components/home/CarouselBestpick.tsx
  frontend/src/components/home/CategoryBox.tsx
  frontend/src/components/home/HamburgerMenu.tsx
  frontend/src/components/product-list/ProductItem.tsx
  frontend/src/types/products.ts
Labels: ⚠️ bug, 🌈 feature

#105 [반재영] seedData 추가(상품 통일, 리뷰 추가, 회원 추가)
  backend/public/images/product1-01.jpg
  backend/public/images/product1-02.jpg
  backend/public/images/product3-01.jpg
  backend/public/images/product3-02.jpg
  backend/public/images/product4-01.jpg
  backend/public/images/product4-02.jpg
  backend/public/images/product5-01.jpg
  backend/public/images/product5-02.jpg
  backend/public/images/product7-01.jpg
  backend/public/images/product7-02.jpg
  backend/seedData.js
Labels: 🔋 enhancement

#104 [신명희] discountPercentage 나오도록 수정
  backend/routes/products.js
  frontend/src/components/product-list/ProductItem.tsx
  frontend/src/types/products.ts
Labels: ⚠️ bug, 🌈 feature

#106 [김혜빈] 상품 상세 페이지 캐러셀 구현, rating 별점 이미지 구현
  backend/seedData.js
  frontend/src/components/product/Photos.tsx
  frontend/src/components/product/Review.tsx
  frontend/src/components/product/ReviewDetailModal.tsx
  frontend/src/components/product/ReviewStar.tsx
  frontend/src/components/product/reviewsTab.tsx
Labels: 🌈 feature

#108 [신명희] 상품 사진 안나오는 문제 해결
  backend/routes/products.js
  backend/seedData.js
  frontend/public/images/home/icon-cap.png
  frontend/src/components/home/BestPick.tsx
  frontend/src/components/home/CarouselBestpick.tsx
  frontend/src/components/home/CategoryBox.tsx
  frontend/src/components/product-list/ProductItem.tsx
  frontend/src/types/products.ts
Labels: ⚠️ bug, 🌈 feature

#111 [김지균] 주문/결제 폼데이터 DB 등록(order)
  backend/models/Order.js
  backend/routes/orders.js
  frontend/src/components/paymentorder/OrderProductList.tsx
  frontend/src/components/paymentorder/PriceRow.tsx
  frontend/src/components/paymentorder/ShippingInformation.tsx
  frontend/src/components/paymentorder/TotalPrice.tsx
  frontend/src/routes/pages/PayMentOrderPage.tsx
  frontend/src/services/order.ts
  frontend/src/types/orders.ts
Labels: ⚠️ bug, 🌈 feature

#112 [김혜빈] 상세 페이지 리뷰 평균값 구현 및 사진 데이터 예외처리
  frontend/src/components/product/AverageRating.tsx
  frontend/src/components/product/Review.tsx
  frontend/src/components/product/reviewsTab.tsx
  frontend/src/hooks/useProduct.ts
  frontend/src/types/products.ts
  frontend/src/types/reviews.ts
Labels: 🌈 feature

#110 [신명희] ProductItem path 공백 제거
  frontend/src/components/product-list/ProductItem.tsx
  frontend/src/hooks/useCart.ts
Labels: ⚠️ bug, 🌈 feature

#109 [반재영] 주문내역과 리뷰내역에서 상품페이지 연결, url 경로에 회원id 제거, 로그인 에러 처리
  backend/routes/users.js
  backend/seedData.js
  frontend/src/components/home/MainIconButton.tsx
  frontend/src/components/mypage/PointAndReview.tsx
  frontend/src/components/mypage/RecentOrderItems.tsx
  frontend/src/components/mypage/RecentOrders.tsx
  frontend/src/components/mypage/ReviewTableBody.tsx
  frontend/src/components/mypage/UserDetailPreview.tsx
  frontend/src/components/mypage/UserInfoEditForm.tsx
  frontend/src/components/mypage/UserInfoPreview.tsx
  frontend/src/components/mypage/UserVerification.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/LoginPage.tsx
  frontend/src/services/user.ts
  frontend/src/types/orders.ts
  frontend/src/types/users.ts
Labels: ⚠️ bug, 🌈 feature

#114 [김혜빈] count statate 공유, 사이즈 버튼, 총합 가격 구현, 모덜창 데이터 연결
  frontend/src/components/product/Details.tsx
  frontend/src/components/product/Review.tsx
  frontend/src/components/product/ReviewDetailModal.tsx
  frontend/src/components/product/SelectedItem.tsx
  frontend/src/components/product/reviewsTab.tsx
Labels: 🌈 feature

#115 [반재영] 메인 아이콘 툴팁 추가, 햄버거메뉴 마이페이지 연결 수정
  frontend/src/components/home/BestPick.tsx
  frontend/src/components/home/HamburgerMenu.tsx
  frontend/src/components/home/MainIconButton.tsx
  frontend/src/components/product-list/Sidebar.tsx
Labels: 🌈 feature

#116 [김지균] 주문완료 버튼 클릭시 페이지 이동 / 주소 api 추가
  frontend/index.html
  frontend/src/components/paymentorder/ShippingInformation.tsx
  frontend/src/components/paymentorder/TotalPrice.tsx
  frontend/src/routes/pages/PayMentPage.tsx
  frontend/src/services/order.ts
  frontend/src/types/orders.ts
Labels: 🌈 feature

#118 [신명희] 상품 상세 페이지 할인 퍼센트 나오도록 수정
  backend/routes/products.js
  frontend/src/components/product/Details.tsx
  frontend/src/hooks/useProduct.ts
  frontend/src/types/products.ts
Labels: ⚠️ bug, 🌈 feature

#120 [김지균] 바로구매 버튼 Link 생성
  backend/routes/orders.js
  frontend/src/components/paymentorder/ShippingInformation.tsx
  frontend/src/components/paymentorder/TotalPrice.tsx
  frontend/src/components/product/Details.tsx
  frontend/src/routes/pages/PayMentOrderPage.tsx
  frontend/src/services/order.ts
  frontend/src/types/orders.ts
Labels: ⚠️ bug

#122 [김지균] 상품 등록 데이터 DB 등록
  backend/routes/orders.js
  frontend/src/components/paymentorder/TotalPrice.tsx
  frontend/src/routes/pages/PayMentOrderPage.tsx
  frontend/src/services/order.ts
  frontend/src/services/orderItem.ts
Labels: 🌈 feature

#123 [반재영] 주문현황 카운트 추가, 마이페이지 디자인 수정
  frontend/src/components/mypage/OrderStatusPreview.tsx
  frontend/src/components/mypage/PointAndReview.tsx
  frontend/src/components/mypage/PointList.tsx
  frontend/src/components/mypage/PointTable.tsx
  frontend/src/components/mypage/Points.tsx
  frontend/src/components/mypage/UserDetailPreview.tsx
  frontend/src/components/mypage/UserInfoEditForm.tsx
  frontend/src/components/mypage/UserInfoPreview.tsx
  frontend/src/mocks/points.json
  frontend/src/routes/pages/MyPage.tsx
  frontend/src/utils/getTotalAmount.ts
Labels: 🎨 layout, 🌈 feature

#124 [신명희] 상품 목록 페이지가 아닌 페이지에서 카테고리 물결 안 보이도록 하는 기능 로직 수정
  frontend/src/components/home/CategoryBox.tsx
  frontend/src/hooks/useCategory.ts
Labels: ⚠️ bug, 🌈 feature

#125 [김혜빈] 3d 피버 세팅/ 상세페이지 사진 DB연결, 상세 페이지 디테일 추가
  backend/seedData.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/image 42.png
  frontend/public/models/womenSwimSuit01.fbx
  frontend/src/components/product/App.tsx
  frontend/src/components/product/Details.tsx
  frontend/src/components/product/Photos.tsx
  frontend/src/components/product/Review.tsx
  frontend/src/components/product/ReviewDetailModal.tsx
  frontend/src/routes/pages/ProductDetailPage.tsx
Labels: ⚠️ bug, 🌈 feature

#126 [신명희] 상품 상세페이지, 주문페이지 수정(변수명, 주문 데이터)
  backend/routes/orders.js
  frontend/src/components/paymentorder/OrderProductList.tsx
  frontend/src/components/paymentorder/ShippingInformation.tsx
  frontend/src/components/paymentorder/TotalPrice.tsx
  frontend/src/components/product/Details.tsx
  frontend/src/components/product/SelectedItem.tsx
  frontend/src/routes/pages/PayMentOrderPage.tsx
  frontend/src/services/order.ts
  frontend/src/types/orders.ts
Labels: 🔋 enhancement, 🔨 invalid, 🌈 feature

#128 feat: 상세페이지 3djs 추가
  frontend/src/components/product/DetailsTab.tsx
  frontend/src/components/product/js.tsx
Labels: 🌈 feature

#129 fix: 가격 포맷 공통되게 수정
  frontend/src/components/cart/CartProduct.tsx
  frontend/src/components/cart/CartTotalPrice.tsx
  frontend/src/components/product-list/ProductItem.tsx
  frontend/src/components/product/Details.tsx
  frontend/src/components/product/SelectedItem.tsx
Labels: 🔋 enhancement, 🌈 feature

#130 [김지균] 주문페이지 URL 주소명 변경
  frontend/src/components/paymentorder/PossessionPoint.tsx
  frontend/src/routes/index.tsx
Labels: 🔋 enhancement

#131 [김지균] 파일명 변경
  frontend/src/components/order/Component.tsx
  frontend/src/components/order/MeansPayment.tsx
  frontend/src/components/order/OrderProductList.tsx
  frontend/src/components/order/PossessionPoint.tsx
  frontend/src/components/order/PriceRow.tsx
  frontend/src/components/order/ShippingInformation.tsx
  frontend/src/components/order/TotalPrice.tsx
  frontend/src/components/product/Details.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/OrderPage.tsx
  frontend/src/routes/pages/OrderThanksPage.tsx
Labels: 📄 documentation

#134 [반재영] 버튼 태그 오류 수정
  frontend/src/components/common/Header.tsx
  frontend/src/components/home/MainIconButton.tsx
Labels: ⚠️ bug

#133 [신명희] 장바구니 관련 기능 구현
  backend/routes/carts.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/cart/Cart.tsx
  frontend/src/components/cart/CartProduct.tsx
  frontend/src/components/cart/CartProductList.tsx
  frontend/src/components/cart/CartTotalPrice.tsx
  frontend/src/components/order/TotalPrice.tsx
  frontend/src/components/product/Details.tsx
  frontend/src/components/product/reviewsTab.tsx
  frontend/src/contexts/CartContext.tsx
  frontend/src/hooks/useCart.ts
  frontend/src/routes/pages/OrderPage.tsx
  frontend/src/services/cart.ts
  frontend/src/types/cart.ts
  frontend/src/types/orders.ts
Labels: ⚠️ bug, 🌈 feature

#136 [전체] 회원정보수정, 회원가입 폼 디자인 통일
  frontend/src/components/join/InputField.tsx
  frontend/src/components/mypage/UserInfoEditForm.tsx
  frontend/src/routes/pages/JoinPage.tsx
Labels: 🎨 layout

#135 [전체] 장바구니, 회원 가입, 아이디/비밀번호 찾기, 로그인, 메인 캐러셀 디자인 수정
  backend/seedData.js
  frontend/src/components/cart/Cart.tsx
  frontend/src/components/cart/CartProductList.tsx
  frontend/src/components/cart/CartTotalPrice.tsx
  frontend/src/components/home/BestPick.tsx
  frontend/src/components/home/CarouselBestpick.tsx
  frontend/src/components/home/MainIconButton.tsx
  frontend/src/components/join/Agrees.tsx
  frontend/src/components/login/FindIdPwdTab.tsx
  frontend/src/components/main/Component.tsx
  frontend/src/components/mypage/PointAndReview.tsx
  frontend/src/components/mypage/PointTable.tsx
  frontend/src/components/signIn/Component.tsx
  frontend/src/components/ui/tabs.tsx
  frontend/src/routes/pages/FindIdPwdPage.tsx
  frontend/src/routes/pages/JoinPage.tsx
  frontend/src/routes/pages/LoginPage.tsx
  frontend/src/routes/pages/MyPage.tsx
  frontend/src/routes/pages/ProductListPage.tsx
Labels: 🔋 enhancement, 🎨 layout

#137 [반재영] 3차 멘토 리뷰 반영
  frontend/src/components/mypage/UserInfoEditForm.tsx
  frontend/src/components/mypage/UserInfoPreview.tsx
  frontend/src/components/mypage/UserVerification.tsx
  frontend/src/routes/pages/LoginPage.tsx
Labels: ⚠️ bug, 🔨 invalid

#139 [김지균] 주문결제페이지 입력검증
  backend/routes/orders.js
  frontend/src/components/order/MeansPayment.tsx
  frontend/src/components/order/ShippingInformation.tsx
  frontend/src/components/order/TotalPrice.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/pages/OrderPage.tsx
  frontend/src/services/order.ts
Labels: 🔋 enhancement

#141 [김지균, 반재영] 주문인 이름 불러오기
  backend/routes/orders.js
  frontend/src/components/order/ShippingInformation.tsx
  frontend/src/services/user.ts
Labels: 🌈 feature

#138 [김혜빈] 상세페이지 조건 3D 모델링 로드 구현
  frontend/public/models/cap.fbx
  frontend/public/models/fins.fbx
  frontend/public/models/menSwimSuit01.fbx
  frontend/public/models/menSwimSuit02.fbx
  frontend/public/models/towel.fbx
  frontend/public/models/womenSwimSuit02.fbx
  frontend/src/components/product/DetailsTab.tsx
  frontend/src/components/product/js.tsx
  frontend/src/routes/pages/ProductDetailPage.tsx
Labels: 🌈 feature

#142 [반재영] 잘못삭제된 코드 추가
  frontend/src/services/user.ts
Labels: ⚠️ bug

#144 [신명희] 주소 노출 된 부분 env 파일에서 받아오도록 수정, script 수정
  backend/app.js
  backend/config/config.js
  backend/package.json
  frontend/package.json
  frontend/src/services/index.ts
Labels: 🔨 invalid
