Repository ormcamp-fe-3rd/swim360, pull requests merged in 2025-01, with the labels that each got.

#153 [신명희] 선택한 상품 없을 시에도 장바구니, 구매 넘어가는 문제 해결(전체 수량 0 여부 판단하도록 수정)
  frontend/src/components/product/Details.tsx
Labels: ⚠️ bug

#157 [김지균] input 값 입력시 검증되면 배경색 바뀌어서 확인가능하도록 수정, 포인트 최솟값 0으로 설정
  frontend/src/components/join/InputField.tsx
  frontend/src/components/order/MeansPayment.tsx
  frontend/src/components/order/PossessionPoint.tsx
  frontend/src/components/order/ShippingInformation.tsx
  frontend/src/routes/pages/JoinPage.tsx
Labels: ⚠️ bug

#158 [김혜빈] thankyouorder 접근성 오류 수정
  frontend/src/routes/pages/OrderThanksPage.tsx
Labels: ⚠️ bug

#159 [반재영] 회원정보 수정 입력폼 검증 수정, 회원정보수정 기능 추가, 마이페이지 접근성 수정
  backend/routes/users.js
  frontend/src/components/mypage/UserInfoEditForm.tsx
  frontend/src/components/mypage/UserVerification.tsx
  frontend/src/routes/pages/MyPage.tsx
  frontend/src/routes/pages/PointAndReviewPage.tsx
  frontend/src/services/user.ts
Labels: ⚠️ bug, 🌈 feature

#160 [반재영] 메인 케러셀 탭인덱스 수정
  frontend/src/components/home/BestPick.tsx
  frontend/src/components/home/CarouselBanner.tsx
  frontend/src/components/home/CarouselBestpick.tsx
  frontend/src/components/home/MainIconButton.tsx
Labels: ⚠️ bug

#161 [전체] 버그 수정
  backend/routes/users.js
  frontend/src/components/common/Footer.tsx
  frontend/src/components/home/BestPick.tsx
  frontend/src/components/home/CarouselBanner.tsx
  frontend/src/components/home/CarouselBestpick.tsx
  frontend/src/components/home/MainIconButton.tsx
  frontend/src/components/join/Agrees.tsx
  frontend/src/components/join/InputField.tsx
  frontend/src/components/mypage/UserInfoEditForm.tsx
  frontend/src/components/mypage/UserVerification.tsx
  frontend/src/components/order/MeansPayment.tsx
  frontend/src/components/order/PossessionPoint.tsx
  frontend/src/components/order/ShippingInformation.tsx
  frontend/src/routes/pages/JoinPage.tsx
  frontend/src/routes/pages/MyPage.tsx
  frontend/src/routes/pages/OrderThanksPage.tsx
  frontend/src/routes/pages/PointAndReviewPage.tsx
  frontend/src/services/user.ts
Labels: ⚠️ bug, 🔋 enhancement

#162 [반재영] 주문 페이지 point 사용 안되도록 수정
  frontend/src/components/order/PossessionPoint.tsx
Labels: ⚠️ bug
